{{ if .Values.tautulli.enabled }}
---
### CONFIGMAPS
### INIT-CONTAINER
apiVersion: v1
data:
  config.ini: |
    [General]
    http_root = /tautulli
    launch_browser = 0
  init-tautulli.sh: |
    #!/bin/bash
    echo "### Initializing config"
    if [ ! -f /tautulli-config/config.ini ]; then
      cp -n /init-tautulli/config.ini /tautulli-config/config.ini
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-tautulli-cm
---
### APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: tautulli-config
data:
  PGID: "{{ .Values.general.pgid }}"
  PUID: "{{ .Values.general.puid }}"
---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-mediaserver.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "k8s-mediaserver.selectorLabels" . | nindent 8}}
        app: tautulli
    spec:
      initContainers:
        - name: config-tautulli
          image: docker.io/ubuntu:groovy
          command: ["/init-tautulli/init-tautulli.sh"]
          volumeMounts:
            - mountPath: /init-tautulli
              name: init-files-tautulli
          {{- if .Values.tautulli.volume }}
            - name: {{ .Values.tautulli.volume.name }}
              mountPath: /tautulli-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /tautulli-config
              subPath: "{{ .Values.general.storage.subPaths.config }}/tautulli"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: tautulli-config
          image: "{{ .Values.tautulli.container.image }}:{{ .Values.tautulli.container.tag | default .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.tautulli.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - name: tautulli-port
              containerPort: {{ .Values.tautulli.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.tautulli.volume }}
            - name: {{ .Values.tautulli.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /config
              subPath: "{{ .Values.general.storage.subPaths.config }}/tautulli"
          {{- end }}
          {{- with .Values.tautulli.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{ if not .Values.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{- if .Values.tautulli.volume }}
        - name: {{ .Values.tautulli.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.tautulli.volume.name }}
        {{- end }}
        - name: init-files-tautulli
          configMap:
            defaultMode: 493
            name: init-tautulli-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end }}
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tautulli.service.type }}
  ports:
    - port: {{ .Values.tautulli.service.port }}
      targetPort: {{ .Values.tautulli.container.port }}
      protocol: TCP
{{ if eq .Values.tautulli.service.type "NodePort" }}
      nodePort: {{ .Values.tautulli.service.nodePort }}
{{ end }}
      name: tautulli-port
  selector:
    app: tautulli
---
{{ if .Values.tautulli.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: tautulli-lb
  annotations:
    {{- include .Values.tautulli.service.extraLBService.annotations . | nindent 4 }}
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.tautulli.service.port }}
      targetPort: {{ .Values.tautulli.container.port }}
      protocol: TCP
      name: tautulli-port
  selector:
    app: tautulli
{{ end }}
---
### INGRESS ###
{{ if .Values.tautulli.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  labels:
    {{- include "k8s-mediaserver.labels" . | nindent 4 }}
  {{- with .Values.tautulli.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.tautulli.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.tautulli.ingress.tls.secretName }}
{{ end }}
  ingressClassName: {{ .Values.general.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.tautulli.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: {{ .Values.tautulli.service.port }}
{{ end }}
{{ end }}